@base_address = http://localhost:5208/api/order

GET {{base_address}}
Content-Type: application/json

###

GET {{base_address}}/1
Content-Type: application/json

###

GET {{base_address}}?pageSize=3&pageNumber=0
Content-Type: application/json

###

POST {{base_address}}
Content-Type: application/json

{
    "SenderCity":"Москва",
    "RecipientCity": "Магнитогорск",
    "SenderAddress": "ул. Арцеулловская 4",
    "RecipientAddress": "ул. Пяточника 134",
    "Weight": 5000,
    "Date": "2025-10-05"
}